### ISSUE TITLE
Design webpage

### ISSUE THREAD

**Issue by JohnLe01** [PriceGuyS/pg-frontend#1]
Should design the layout and look of webpage. This includes the home page, the browse page, the search page, and the about page. Would be nice to have a rough sketch of the design posted.
- [x] Design home page
- [x] Design browse page
- [x] Design search page
- [x] Design about page
- [x] Design Item page

**Comment by JohnLe01** [comment]
We definitely need to design the look of everything before moving forward. I'll takle thiis on. Not sure what software to use for wireframing... might even use the good ol' pen and paper.

**Comment by DavisFrench** [comment]
I created a ghetto UI That displays the image, link to item, price, location, and where it ships to.

**Comment by DavisFrench** [comment]
Ghetto display is back up

**Comment by JohnLe01** [comment]
Home page design: Users can either click the "Home," "Browse," and "About" pages, enter in a game title in the search bar to get sent to a Search Results page, or click 1 of the 3 or 6 items being featured at the home page:

![Screen Shot 2017-11-30 at 7.21.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a72e9b79081f0011023594/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a37ff1102a4f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ee4806a5d22933810f8ea841dee01ba23da1b82bebf8a48d2f42f67b6d5db1063474f4dcbed5727a19041c95df749e14552ac103267e7752431.png)

**Comment by JohnLe01** [comment]
Browse Page: Users can either search for a game in the search bar, browse through the grid of items on each page, change the number of items they see per page, or filter their results by price, condition, etc.:
![Screen Shot 2017-11-30 at 7.44.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a72e9b79081f0011023594/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a37ff1162f4f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ee4806a5d22933810f8ea841dee01ba23da1b82bebf8a48d2f42f67b6d5db1063474f4dcbed5727a19041c95df749e1455ca5103561ee7f2431.png)

**Comment by JohnLe01** [comment]
About page: simple page that talks about what we do, what they can expect to find on our website, as well as links to our social media sites (if we have any in the future) and github. There can be small icons that lead you to our github, twitter, etc. when you click them.
![Screen Shot 2017-11-30 at 7.52.03 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a72e9b79081f0011023594/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a37ff117294f5f5c5ecc3c4a4356bcbbd671f3e57862804e0ee4806a5c74c66916a8eed44db701ba22dd4c84b5ee8b4cd2f42f67b6d5db1063474f4dcbed5727a19041c95df749e1455ca2123660e1702431.png)

**Comment by JohnLe01** [comment]
Search page: page that will be shown after user enters in a title in any search bar. User can select the game they were looking for in the search results, or scroll down to view the results. (In a perfect world,) User can select number of results per page.
![Screen Shot 2017-11-30 at 7.59.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a72e9b79081f0011023594/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a37ff117224f5b595ecc3c4a4356bcbbd671f3e57862804e0ee4806a5c74c66916a8eed44db701ba22dd4c84b5ee8b4cd2f42f67b6d5db1063474f4dcbed5727a19041c95df749e14455a41a3267e4742431.png)

**Comment by JohnLe01** [comment]
Item page: page for every time a user looks at the prices for a specific item. Displays lowest price from available stores we have data for, the condition, etc. User can directly go to the respective site to buy by either click on the amazon box to head straight there, or click the ebay box to display a list of the top 10 deals for the specific item.
![Screen Shot 2017-11-30 at 8.07.12 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a72e9b79081f0011023594/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a370f1122c4f5e5d5ecc3c4a4356bcbbd671f3e57862804e0ee4806a5c74c66916a8eed44db701ba22dd4c84b5ee8b4cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df749e14455a1143660e67e2431.png)

**Comment by JohnLe01** [comment]
@DavisFrench @DER1KULOUS @paytonharris @spencergoff @zshumate Finished designing the individual pages. Let me know how they look and if everything looks good to go

**Comment by JohnLe01** [comment]
Gonna close this for now for the burndown chart. Feel free to comment on the design and add to it even if the issue is closed!

**Comment by spencergoff** [comment]
Nice! Have you tested getting all of the item images to appear? Just curious how that works, but I know Davis said he figured out how to pull them in somehow.
