### ISSUE TITLE
Hosting the website

### ISSUE THREAD

**Issue by JohnLe01** [PriceGuyS/pg-frontend#10]
Figure out the various sources we can host our website (preferably for free). Recommendations are Digital Ocean, AWS, or UofL servers

- [ ] Research and the decide on how we will host rwebsite
- [ ] Host website on said source

**Comment by spencergoff** [comment]
I'm looking into https://pages.github.com/ and https://www.000webhost.com/       -Spencer

**Comment by spencergoff** [comment]
And also Amazon Lightsail

**Comment by JohnLe01** [comment]
Finished this. Used Heroku
