### ISSUE TITLE
Design Home page components

### ISSUE THREAD

**Issue by JohnLe01** [PriceGuyS/pg-frontend#2]
Based on initial home page design, break the home page into separate components based on React and OOP principles.
Refer to #1 for home page design
- [x] Break home page design into separate components
- [ ] Sketch/provide design of components

**Comment by DER1KULOUS** [comment]
Home page is in separate components.  Home, Browse, and About are the available tabs.  Main(App) controls the look of header and logo.  Also, controls the flow by calling Menu.jsx.  Menu is the component used for the look and feel of the top tab bar. Browse calls uses the query_Test component to produce the view-able items.

**Comment by JohnLe01** [comment]
:+1:
